version: '3.8'

services:
  touch_showroom:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
    restart: always
    privileged: true
